name: Deploy Microservice
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Version:
    uses: tech3k/actions/.github/workflows/bump-version.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}

  CloudRun:
    needs: Version
    uses: tech3k/actions/.github/workflows/cloud-run.yml@main
    secrets:
      RUN_PROJECT_PRODUCTION: ${{ secrets.RUN_PROJECT_PRODUCTION }}
      RUN_PROJECT_STAGING: ${{ secrets.RUN_PROJECT_STAGING }}
      RUN_SA_KEY: ${{ secrets.RUN_SA_KEY }}

  Review:
    needs: CloudRun
    uses: tech3k/actions/.github/workflows/review-request.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
