name: Bump Version
on:
  workflow_call:
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  BumpVersion:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'main',
              {
                name: 'staging', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          commit_message: Version Bump
