name: Bump Version
on:
  workflow_call:
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  Skip:
    if: ${{ (github.event_name == 'pull_request_target' || github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping Version Bumping since we're in a pull request"
  Bump:
    if: ${{ (github.event_name != 'pull_request_target' && github.event_name != 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'main',
              {
                name: 'staging', 
                prerelease: true
              }
            ]
          extends: |
            semantic-release-npm-github-publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
