name: Bump Version
on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  BumpVersion:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'main',
              {
                name: 'staging', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: 000000000000
