name: Bump Version
on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  BumpVersion:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Run the semantic versioning
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release --branches ${{ '[\'main\']' }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Version Bump
