name: Bump Version
on:
  workflow_call:
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  BumpVersion:
    if: ${{ (github.event_name != 'pull_request_target' && github.event_name != 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'main',
              {
                name: 'staging', 
                prerelease: true
              }
            ]
          extends: |
            semantic-release-npm-github-publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
