name: Expo Deployment
on:
  workflow_call:
    inputs:
      APPLE_APP_ID:
        required: true
        type: string
    secrets:
      EXPO_TOKEN:
        required: true
      EXPO_APPLE_PASSWORD:
        required: true
      EXPO_APPLE_ID:
        required: true

jobs:
  Skip:
    if: ${{ github.ref_name != 'main' && github.ref_name != 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping as we are not a main or staging branch"
  BuildIos:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: Prebuild
        run: yarn expo prebuild --clean
      - name: Build on EAS
        run: yarn expo build --platform ios --non-interactive --profile ${{ github.ref_name }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  BuildAndroid:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: Prebuild
        run: yarn expo prebuild --clean
      - name: Build on EAS
        run: yarn expo build --platform android --non-interactive --profile ${{ github.ref_name }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  DeployIos:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
    needs:
      - BuildIos
    name: Submit iOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: Submit to AppStore
        run: yarn expo submit -p ios --latest --profile=${{ github.ref_name }}
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_PASSWORD }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  DeployAndroid:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
    needs:
      - BuildAndroid
    name: Submit Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: Submit to Google Play
        run: yarn expi submit -p android --latest --profile=${{ github.ref_name }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  publishChanges:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
    needs:
      - DeployIos
      - DeployAndroid
    name: Publish Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: Install dependencies
        run: yarn install
      - name: Publish
        run: yarn expo publish --release-channel ${{ github.ref_name }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
