name: Netlify Deployment
on: workflow_call

jobs:
  Setup:
    name: Setup Repository
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    outputs:
      cachepath: ${{ steps.generate_cache_path.outputs.cachepath }}
    steps:
      - name: Checkout Latest Version
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      - name: Checkout Latest Version (PR)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Generate Cache Path
        id: generate_cache_path
        run: echo "::set-output name=cachepath::${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}-yarn-${{ hashFiles('**/yarn.lock') }}"
      - uses: actions/cache@v2
        with:
          path: ./
          key: ${{ steps.generate_cache_path.outputs.cachepath }}
      - name: Install Dependencies
        run: yarn install

  Test:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/cache@v2
        with:
          path: ./
          key: ${{ jobs.Setup.outputs.cachepath }}
      - name: Test
        run: yarn test

  Build:
    name: Build Website
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/cache@v2
        with:
          path: ./
          key: ${{ jobs.Setup.outputs.cachepath }}
      - name: Build
        run: yarn build

  Publish:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    needs:
      - Test
      - Build
    steps:
      - uses: actions/cache@v2
        with:
          path: ./
          key: ${{ jobs.Setup.outputs.cachepath }}
      - name: Build
        run: yarn build
