name: Netlify Deployment
on:
  workflow_call:
    secrets:
      NETLIFY_URL:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_SITE_STAGING_ID:
        required: true

jobs:
  Setup:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    outputs:
      cachepath: ${{ steps.generate_cache_path.outputs.cachepath }}
    steps:
      - name: Checkout Latest Version
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      - name: Checkout Latest Version (PR)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Generate Cache Path
        id: generate_cache_path
        run: echo "::set-output name=cachepath::${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}-yarn-${{ hashFiles('**/yarn.lock') }}"
      - uses: actions/cache@v2
        with:
          path: ./**/*
          key: ${{ steps.generate_cache_path.outputs.cachepath }}
      - name: Install Dependencies
        run: yarn install

  Test:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/cache@v2
        with:
          path: ./**/*
          key: ${{ needs.Setup.outputs.cachepath }}
      - name: Test
        run: yarn test

  Build:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/cache@v2
        with:
          path: ./**/*
          key: ${{ needs.Setup.outputs.cachepath }}
      - name: Build
        run: yarn build

  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref_name == 'main' && 'Production') || ((github.event_name != 'pull_request_target' && github.event_name != 'pull_request') && 'Staging') || 'Preview' }}
      url: ${{ steps.deployment_status.outputs.url }}
    needs:
      - Setup
      - Test
      - Build
    steps:
      - uses: actions/cache@v2
        with:
          path: ./**/*
          key: ${{ needs.Setup.outputs.cachepath }}
      - name: Publish
        id: netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy ${{ (github.event_name != 'pull_request_target' && '--prod') || '' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ ((github.ref_name != 'main' || github.event_name == 'pull_request_target') && secrets.NETLIFY_SITE_STAGING_ID) || secrets.NETLIFY_SITE_ID }}
      - name: Update Deployment Status
        if: ${{ success() }}
        id: deployment_status
        run: echo "::set-output name=url::${{ (github.ref_name == 'main' && format('https://{0}', secrets.NETLIFY_URL)) || (github.event_name != 'pull_request_target' && format('https://staging.{0}', secrets.NETLIFY_URL)) || steps.netlify.outputs.NETLIFY_URL }}"
